task_management/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import path, include, reverse_lazy
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('tasks:list'))),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/tasks/urls.py
from tasks import views
from django.urls import path

app_name = 'tasks'

urlpatterns = [
    path('list/', views.ListTasksView.as_view(), name='list'),
    path('create/', views.CreateTaskView.as_view(), name='create'),
    path('<str:pk>/', views.TaskDetailsView.as_view(), name='details'),
    path('delete/<str:pk>/', views.DeleteTaskView.as_view(), name='delete'),
    path('update/<str:pk>/', views.UpdateTaskView.as_view(), name='update'),

]

task_management/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('sign-out/', views.SignOutView.as_view(), name='sign-out'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
]

task_management/templates/shared/footer.html
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Task Management</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        Repo <a href="https://github.com/Ali1995Askar/task-management">Source Code</a>
    </div>
</footer><!-- End Footer -->

task_management/templates/shared/header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'tasks:list' %}" class="logo d-flex align-items-center">
            <img src="{% static 'img/logo.png' %}" alt="logo">
            <span class="d-none d-lg-block">Task Management</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div>

    <nav class="header-nav ms-auto">
        {% if user.is_authenticated %}
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="{% static 'img/user-icon.png' %}" alt="logo">
                        <span class="d-none d-md-block dropdown-toggle ps-2">
                            {{ user.username }}
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            {% if user.is_authenticated %}
                                {{ user.email }}
                            {% endif %}
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href={% url 'users:sign-out' %}>
                                <span>Sign Out</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        {% endif %}
    </nav>
</header>

task_management/templates/shared/sidebar.html
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-wrench-adjustable"></i><span>Tasks</span><i
                    class="bi bi-chevron-down ms-auto"></i>
            </a>

            <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'tasks:create' %}">

                        <i class="bi bi-circle"></i><span>Add New Task</span>
                    </a>
                </li>

                <li>

                    <a href="{% url 'tasks:list' %}">
                        <i class="bi bi-circle"></i><span>My Tasks</span>
                    </a>
                </li>
            </ul>
        </li>


        <li class="nav-heading"><i class="bi bi-gear"></i> &nbsp; Account</li>
        <li class="nav-item">
            <a class="nav-link collapsed" href={% url 'users:sign-out' %}>
                <i class="bi bi-box-arrow-in-left"></i>
                <span>Sign out</span>
            </a>
            <a class="nav-link collapsed" href={% url 'users:change-password' %}>
                <i class="bi bi-file-lock2"></i>
                <span>Change password</span>
            </a>
        </li>
    </ul>
</aside>