task_management/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import path, include, reverse_lazy
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('tasks:list'))),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('sign-out/', views.SignOutView.as_view(), name='sign-out'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
]

task_management/users/models.py
from django.db import models
from django.conf import settings

from core.utils import AbstractBaseModel


class Profile(AbstractBaseModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    max_tasks_per_day = models.IntegerField(default=10)

    def __str__(self):
        return f'{self.user}: max tasks: {self.max_tasks_per_day}'

task_management/users/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.forms import UsernameField, PasswordChangeForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model, password_validation

User = get_user_model()


class SignupForm(auth_forms.UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', "autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control', "autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'type': 'text',
                                                 'required': True,
                                                 'name': 'first_name',
                                                 'id': 'first_name'}),

            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'type': 'text',
                                                'required': True,
                                                'name': 'last_name',
                                                'id': 'last_name'}),

            'email': forms.EmailInput(attrs={'class': 'form-control',
                                             'type': 'email',
                                             'required': True,
                                             'name': 'email',
                                             'id': 'email'}),

            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'type': 'text',
                                               'name': 'username',
                                               'id': 'username'}),

        }


class SigninForm(auth_forms.AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                           "autofocus": True,
                                                           'type': 'username',
                                                           'name': 'username',
                                                           'id': 'username', }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'type': 'password',
                                          'name': 'password',
                                          'id': 'password'}),
    )


class ChangePasswordForm(PasswordChangeForm):

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)

        self.fields['old_password'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'name': 'old_password',
            'id': 'old_password',
        })

        self.fields['new_password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'name': 'new_password1',
            'id': 'new_password1',
            'help_text': password_validation.password_validators_help_text_html(),
        })

        self.fields['new_password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'name': 'new_password2',
            'id': 'new_password2',
        })

task_management/users/views.py
from users import forms
from django.contrib.auth import logout, login
from django.views import generic, View
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from core.utils import anonymous_user_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, PasswordChangeView


@method_decorator(anonymous_user_required, name='dispatch')
class SignUpView(generic.CreateView):
    form_class = forms.SignupForm
    success_url = reverse_lazy("tasks:list")
    template_name = "users/signup.html"


@method_decorator(anonymous_user_required, name='dispatch')
class SignInView(LoginView):
    template_name = 'users/signin.html'
    form_class = forms.SigninForm


@method_decorator(login_required, name='dispatch')
class ChangePasswordView(PasswordChangeView):
    form_class = forms.ChangePasswordForm
    template_name = 'users/change-password.html'
    success_url = reverse_lazy('users:signin')


@method_decorator(login_required, name='dispatch')
class SignOutView(View):
    template_name = 'users/sign-out.html'

    def get(self, request, *args, **kwargs):
        return render(request, f"{self.template_name}")

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(request)
            return redirect(reverse('users:signin'))
        else:
            return redirect(reverse('tasks:list'))

task_management/templates/users/change-password.html
{% extends "base.html" %}
{% load static %}
{% block title %} Password Change {% endblock %}

{% block content %}


    <main id="main" class="main">
        <div class="pagetitle mb-3">
            <h1>Change Password Form</h1>

        </div><!-- End Page Title -->
        <section>
            <section class="section">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Change Password Form</h5>
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <label for="inputText" class="col-sm-6  col-form-label">Old password</label>
                                        <div class="col-sm-10">
                                            {{ form.old_password }}
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="inputText" class="col-sm-6  col-form-label"> New
                                            password</label>

                                        <div class="col-sm-10">
                                            {{ form.new_password1 }}
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="inputText" class="col-sm-6 col-form-label">Confirm New
                                            Password</label>
                                        <div class="col-sm-10">
                                            {{ form.new_password2 }}
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        {% if form.errors %}
                                            <small class="form-text text-muted ">
                                                {{ form.errors }}
                                            </small>
                                        {% endif %}
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-primary">Change Password</button>
                                        </div>
                                    </div>

                                </form><!-- End General Form Elements -->

                            </div>
                        </div>

                    </div>
                    <div class="col-lg-1"></div>
                </div>
            </section>

        </section>
    </main>
{% endblock content %}

task_management/templates/users/sign-out.html
{% extends "base.html" %}
{% block title %} Sign-out {% endblock %}
{% block content %}
    <main>
        <div class="container">
            <section
                    class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
                <div class="row">
                    <div class="col-xxl-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">
                                    Are you sure you want to Logout ?</h5>
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-danger">
                                            <i class="bi bi-box-arrow-left"></i> &nbsp;Logout
                                        </button>
                                        <a href="{% url 'tasks:list' %}" class="btn btn-primary">
                                            Back To Tasks&nbsp;<i class="bi bi-box-arrow-right"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

task_management/templates/users/signin.html
{% extends "base.html" %}
{% load static %}
{% block title %} Signin {% endblock %}
{% block sidebar %} {% endblock %}

{% block content %}
    <main>
        <div class="container">
            <section
                    class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                            <div class="d-flex justify-content-center py-4">
                                <img src="{% static 'img/logo.png' %}" alt="" style="height: 50px; width: 75px;">
                            </div>

                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                                        <br>
                                    </div>

                                    <form method="post" class="row g-3 needs-validation">
                                        {% csrf_token %}

                                        <div class="col-12">
                                            <label for="yourUsername" class="form-label">Username</label>
                                            <div class="input-group has-validation">
                                                <span class="input-group-text" id="inputGroupPrepend">@</span>
                                                {{ form.username }}
                                                <div class="invalid-feedback">Please enter your Username.</div>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <label for="yourPassword" class="form-label">Password</label>
                                            {{ form.password }}
                                            <div class="invalid-feedback">Please enter your password!</div>
                                        </div>

                                        <div class="col-12">
                                            {% if form.errors %}
                                                <small class="form-text text-muted ">
                                                    Wrong username or password.
                                                </small>
                                            {% endif %}
                                        </div>
                                        <div class="col-12">
                                            <button class="btn btn-primary w-100" type="submit">Login</button>
                                        </div>
                                        <div class="col-12">
                                            <p class="small mb-0">Don't have account? <a
                                                    href={% url 'users:signup' %}>Create an account</a></p>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

task_management/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %} Signup {% endblock %}
{% block sidebar %} {% endblock %}
{% block content %}
    <main>
        <div class="container">
            <section
                    class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">

                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                            <div class="d-flex justify-content-center py-4" style="margin-top: 15%;">
                                <a href='#'>
                                    <img src="{% static 'img/logo.png' %}" alt="" style="height: 50px; width: 75px;">
                                </a>
                            </div>

                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                                        <br>
                                    </div>

                                    <form method="post" class="row g-3 needs-validation">
                                        {% csrf_token %}
                                        <div class="col-12">
                                            <label for="email" class="form-label"> Username</label>
                                            {{ form.username }}
                                            <small class="form-text text-muted "> {{ form.username.errors }}</small>
                                        </div>

                                        <div class="col-12">
                                            <label for="name" class="form-label">First Name</label>
                                            {{ form.first_name }}
                                            <small class="form-text text-muted "> {{ form.first_name.errors }}</small>
                                        </div>
                                        <div class="col-12">
                                            <label for="name" class="form-label">Last Name</label>
                                            {{ form.last_name }}
                                            <small class="form-text text-muted "> {{ form.last_name.errors }}</small>
                                        </div>

                                        <div class="col-12">
                                            <label for="email" class="form-label"> Email</label>
                                            {{ form.email }}
                                            <small class="form-text text-muted "> {{ form.email.errors }}</small>
                                        </div>

                                        <div class="col-12">
                                            <label for="Password1" class="form-label">Password</label>
                                            {{ form.password1 }}
                                            <div class="invalid-feedback">Please enter your password!</div>
                                        </div>

                                        <div class="col-12">
                                            <label for="Password2" class="form-label">Re-Password</label>
                                            {{ form.password2 }}
                                        </div>
                                        <small class="form-text text-muted "> {{ form.password2.errors }}</small>

                                        <div class="col-12"><br></div>

                                        <div class="col-12">
                                            <button class="btn btn-primary w-100" type="submit">Create Account</button>
                                        </div>
                                        <div class="col-12">
                                            <p class="small mb-0">Already have an account?
                                                <a href={% url 'users:signin' %}>signin</a></p>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock content %}