task_management/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import path, include, reverse_lazy
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('tasks:list'))),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/tasks/urls.py
from tasks import views
from django.urls import path

app_name = 'tasks'

urlpatterns = [
    path('list/', views.ListTasksView.as_view(), name='list'),
    path('create/', views.CreateTaskView.as_view(), name='create'),
    path('<str:pk>/', views.TaskDetailsView.as_view(), name='details'),
    path('delete/<str:pk>/', views.DeleteTaskView.as_view(), name='delete'),
    path('update/<str:pk>/', views.UpdateTaskView.as_view(), name='update'),

]

task_management/tasks/models.py
from datetime import date
from django.db import models
from django.conf import settings
from core.utils import AbstractBaseModel


class Task(AbstractBaseModel):
    class Status(models.Choices):
        TODO = 'TODO'
        IN_PROGRESS = 'IN_PROGRESS'
        DONE = 'DONE'

    status = models.CharField(max_length=25, choices=Status.choices, db_index=True, default=Status.TODO)
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    due_date = models.DateField(default=date.today, db_index=True)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   on_delete=models.SET_NULL)

    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    null=True,
                                    blank=True,
                                    on_delete=models.SET_NULL,
                                    related_name='assigned_tasks')

    def __str__(self):
        return f'{self.title} - {self.status}'

task_management/tasks/forms.py
from django import forms
from tasks.models import Task
from users.selectors import UserSelectors


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].widget = forms.Select(
            attrs={
                'class': 'form-control',
                'name': 'assigned_to',
                'id': 'assigned_to',
            },
            choices=UserSelectors.get_users_full_names_if_exists_else_usernames(),
        )

    class Meta:
        model = Task
        exclude = ['created_by']

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'title',
                'id': 'title',
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'name': 'description',
                'id': 'description',
            }),

            'due_date': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
                'name': 'due_date',
                'id': 'due_date',
            }),
            'status': forms.Select(attrs={
                'class': 'form-control',
                'name': 'status',
                'id': 'status',
            }),

        }

task_management/tasks/views.py
from tasks import forms
from tasks.models import Task
from django.views import generic
from tasks.services import TasksServices
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class ListTasksView(generic.ListView):
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'
    queryset = Task.objects.all()

    def get_queryset(self):
        qs = TasksServices.get_user_tasks_with_search_filter(request=self.request)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = TasksServices.group_tasks_by_status(qs=context['tasks'])
        return context


@method_decorator(login_required, name='dispatch')
class CreateTaskView(generic.CreateView):
    model = Task
    form_class = forms.TaskForm
    template_name = 'tasks/create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object, form = TasksServices.check_if_user_can_accept_task(self.request, self.object, form)
        self.object.created_by = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("tasks:details", kwargs={'pk': self.object.pk})


@method_decorator(login_required, name='dispatch')
class TaskDetailsView(generic.DetailView):
    model = Task
    context_object_name = 'task'
    template_name = "tasks/details.html"

    def get_queryset(self):
        qs = TasksServices.get_user_connected_tasks(request=self.request)
        return qs


@method_decorator(login_required, name='dispatch')
class UpdateTaskView(generic.UpdateView):
    model = Task
    form_class = forms.TaskForm
    template_name = 'tasks/update.html'
    context_object_name = 'task'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object, form = TasksServices.check_if_user_can_accept_task(self.request, self.object, form)
        form.save()
        return super().form_valid(form)

    def get_queryset(self):
        qs = TasksServices.get_user_connected_tasks(request=self.request)
        return qs

    def get_success_url(self):
        return reverse_lazy('tasks:details', kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class DeleteTaskView(generic.DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy("tasks:list")

    def get_queryset(self):
        qs = TasksServices.get_user_tasks(request=self.request)
        return qs

task_management/templates/tasks/create.html
{% extends "base.html" %}

{% block title %} Create Task {% endblock %}
{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Task Create Form</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>Tasks</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Task Create Form</h5>
                            <form method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Title</label>
                                    <div class="col-sm-10">
                                        {{ form.title }}
                                        <small>{{ form.title.errors }}</small>
                                    </div>

                                </div>
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Description</label>
                                    <div class="col-sm-10">
                                        {{ form.description }}
                                        <small>{{ form.description.errors }}</small>
                                    </div>
                                </div>

                                <br>
                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Due Date</label>
                                    <div class="col-sm-10">
                                        {{ form.due_date }}
                                        <small>{{ form.due_date.errors }}</small>
                                    </div>
                                </div>
                                <br>

                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Assign To</label>
                                    <div class="col-sm-10">
                                        {{ form.assigned_to }}
                                        <small>{{ form.assigned_to.errors }}</small>
                                    </div>
                                </div>
                                <br>
                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Status</label>
                                    <div class="col-sm-10">
                                        {{ form.status }}
                                        <small>{{ form.status.errors }}</small>
                                    </div>
                                </div>
                                <br>

                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Create</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>


{% endblock content %}

task_management/templates/tasks/delete.html
{% extends "base.html" %}
{% block title %} Delete Task {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">My-Task</a></li>
                    <li class="breadcrumb-item active">Delete</li>
                    <li class="breadcrumb-item active">{{ task.id }}</li>
                </ol>
            </nav>
        </div>

        <section class="section">
            <div class="row">
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><i class="bi bi-trash-fill"></i> Delete Task</h5>
                            <p>Are you sure you want to delete {{ task.title }}</p>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" data-bs-toggle="modal"
                                       data-bs-target="#basicModal" value="Delete Task"/>
                                <a href="{% url 'tasks:details' task.pk %}"
                                   class="btn btn-primary">
                                    Back to Details
                                </a>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </main>

{% endblock content %}

task_management/templates/tasks/details.html
{% extends "base.html" %}

{% block title %} Task Details {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Task Details</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>My Tasks</a></li>
                    <li class="breadcrumb-item active">{{ task.pk }}</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <div class="container">
            <div class="card">

                <div class="card-body">
                    <h5 class="card-title mb-5">{{ task.title }}</h5>
                    <span>{{ task.description }}</span>
                </div>
                <div class="card-footer">
                    <div class="footer-section mb-2">
                        <span class="footer-label">Due Time:</span>
                        <span class="footer-value">{{ task.due_date }}</span>
                    </div>
                    <div class="footer-section mb-2">
                        <span class="footer-label">Status:</span>
                        <span class="footer-value">
                <span class="badge bg-danger">{{ task.status }}</span>
            </span>
                    </div>
                    <div class="footer-section mb-2 ">
                        <span class="footer-label">Assign To:</span>
                        <span class="footer-value">{{ task.assigned_to }}</span>
                    </div>
                    <div class="footer-section mb-2">
                        <span class="footer-label">Created By:</span>
                        <span class="footer-value">{{ task.created_by }}</span>
                    </div>

                    <p class="card-text">
                        <a href="{% url 'tasks:update' task.pk %}" class="btn btn-primary m-lg-2">Update</a>
                        {% if user == task.created_by %}
                            <a href="{% url 'tasks:delete' task.pk %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>

    </main>



{% endblock content %}

task_management/templates/tasks/list.html
{% extends "base.html" %}
{% block title %} My Task {% endblock %}

{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>My Tasks</h1>
            <nav>
                <ol class=" breadcrumb ">
                    <li class="breadcrumb-item"></li>
                    <li class="breadcrumb-item active"><a href={% url 'tasks:list' %}>My Tasks</a></li>
                </ol>
            </nav>
        </div>
        <div class="row">

            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6  mb-3">
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    Today Is: {% now "N j, Y" %}.
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <form class="row g-3">
                <div class="col-md-6">
                    <input id="searchId" type="text" class="form-control" name="search" placeholder="search">
                </div>
                <div class="col-md-4">

                    <select id='filterId' name="filter" class="form-select" aria-label="Default select example">
                        <option value="">All Status</option>
                        <option value="TODO">To Do</option>
                        <option value="IN_PROGRESS">In Progress</option>
                        <option value="DONE">Done</option>
                    </select>
                </div>
                <div class="col-md-2">

                    <button id="searchBtnId" type="submit" class="form-control btn btn-primary rounded-pill mb-3">
                        <i class="bi bi-search"> Search & Filter </i>
                    </button>
                </div>
            </form><!-- End Multi Columns Form -->
        </div>

        <div class="row">
            <div class="col-xxl-4 col-md-4">
                {% for task in todo_tasks %}
                    <a href={% url 'tasks:details' task.pk %}>
                        {% include 'tasks/partials/task_card.html' %}
                    </a>
                {% endfor %}
            </div>
            <div class="col-xxl-4 col-md-4">
                {% for task in in_progress_tasks %}
                    <a href={% url 'tasks:details' task.pk %}>
                        {% include 'tasks/partials/task_card.html' %}

                    </a>
                {% endfor %}
            </div>
            <div class="col-xxl-4 col-md-4">
                {% for task in done_tasks %}
                    <a href={% url 'tasks:details' task.pk %}>
                        {% include 'tasks/partials/task_card.html' %}
                    </a>
                {% endfor %}
            </div>
        </div>


    </main><!-- End #main -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const currentURL = window.location.href;
            var url = new URL(currentURL);
            var filterValue = url.searchParams.get("filter");
            var searchValue = url.searchParams.get("search");

            var filterSelect = document.getElementById("filterId");
            var searchInput = document.getElementById("searchId");

            filterSelect.value = filterValue;
            searchInput.value = searchValue;


            searchInput.addEventListener("input", updateURL);
            filterSelect.addEventListener("change", updateURL);

            function updateURL() {
                var filterValue = filterSelect.value;
                var searchValue = searchInput.value;

                var baseURL = "{% url 'tasks:list' %}?";
                var queryParams = [];

                if (searchValue.trim() !== "") {
                    queryParams.push("search=" + searchValue);
                }
                if (filterValue) {
                    queryParams.push("filter=" + filterValue);
                }


                var newURL = baseURL + queryParams.join("&");
                console.log(newURL)
                window.history.pushState(null, "", newURL);
            }
        });
    </script>
{% endblock content %}

task_management/templates/tasks/update.html
{% extends "base.html" %}

{% block title %} Update Task {% endblock %}
{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Task Update Form</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href='{% url 'tasks:list' %}'>Tasks</a></li>
                    <li class="breadcrumb-item active">Update</li>
                </ol>
            </nav>
        </div>

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Update Task Form</h5>

                            <form method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Title</label>
                                    <div class="col-sm-10">
                                        {{ form.title }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Description</label>
                                    <div class="col-sm-10">
                                        {{ form.description }}
                                    </div>
                                </div>

                                <br>
                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Due Date</label>
                                    <div class="col-sm-10">
                                        {{ form.due_date }}
                                    </div>
                                </div>
                                <br>

                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Assign To</label>
                                    <div class="col-sm-10">
                                        {{ form.assigned_to }}
                                    </div>
                                </div>
                                <br>


                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Status</label>
                                    <div class="col-sm-10">
                                        {{ form.status }}
                                        <small>{{ form.status.errors }}</small>
                                    </div>
                                </div>

                                <br>
                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>

                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}